### ISSUE TITLE
/mapache status

### ISSUE THREAD

**Issue by XuperBryan** [ucsb-cs156-s21/proj-mapache-search#25]
Arman Fluellen:
# ./mapache status

As a user I can /mapache status so that I can verify that the bot is running.

# Acceptance Criteria

- [x] First thing that should be true when story is done, is that the bot should print “Status is ok!” to notify the user that the bot is running.

# Implementation Todos

Testing:

- [x] Back end tests pass and there is adequate coverage

**Comment by Fluellen-Arman** [comment]
Arman Fluellen:
# ./mapache status

As a user I can /mapache status so that I can verify that the bot is running and understand the various status of the other functions. A quick and easy way to see the status of the other functions would be that the status function would print out the number of teams so that the user can have a quick 

# Acceptance Criteria

- [ ] First thing that should be true when story is done, is that the bot should print “Hello World” to notify the user that the bot is running.
- [ ] Second thing that should be true when story is done, is that the bot should print the number of total teams in the slack channel.
- 
...

# Implementation Todos

Front end:

- [ ] First thing that must be done in the front end code.
- [ ] Second thing that must be done in the front end code.
...

Back end:

- [ ] First thing that must be done in the back end code.
- [ ] Second thing that must be done in the back end code.
...


Testing:

- [ ] Front end tests pass and there is adequate coverage
- [ ] Back end tests pass and there is adequate coverage
...

**Comment by andrewhlu** [comment]
Completed in #90.
