### ISSUE TITLE
/mapache teams

### ISSUE THREAD

**Issue by XuperBryan** [ucsb-cs156-s21/proj-mapache-search#26]
# User Story

As a user within the slack channel, I can type /mapache teams in the slack to get the entire list of teams contained within that channel so that I can easily search for a keyword within each subteam to filter out certain keywords that may have appeared in a team which was not desired for the search.

# Acceptance Criteria

- [ ] There will be a text field which lists out the list of teams contained within the slack channel.
- [ ] Only members which are within the slack channel can have access to the list of teams.

# Implementation Todos

Front end:

- [ ] Output the list of teams contained within the slack channel into the text field of the slack
- [ ] Should have an input field to ask the bot to print out the list of slack channels that exist
- [ ] Should have a way to sign in to your account such that the bot knows that you are a member of the slack channel

Back end:
- [ ] Read through the slack channel to obtain the list of teams contained within the channel
- [ ] Create a ListOfTeams database which stores all of the teams read from the above operation onto the MongoDb database after each update occurs
- [ ] Update your ListOfTeams database before each time the program outputs the list of teams such that it makes sure the list of teams that are being output is up to date with any changes that may have occurred.
- [ ] Delete your original database prior to calling update, read, and create such that you can have a fresh database to utilize

Testing:

- [ ] Front end tests pass and there is adequate coverage
- [ ] Back end tests pass and there is adequate coverage

**Comment by kokinarimoto** [comment]
# User Story

As a user within the slack channel, I can search the entire list of teams contained within that channel so that I can easily search for a keyword within each subteam to filter out certain keywords that may have appeared in a team which was not desired for the search.

# Acceptance Criteria

- [ ] There will be a text field which lists out the list of teams contained within the slack channel.
- [ ] Only members which are within the slack channel can have access to the list of teams.

# Implementation Todos

Front end:

- [ ] Output the list of teams contained within the slack channel into the text field of the slack
- [ ] Should have an input field to ask the bot to print out the list of slack channels that exist
- [ ] Should have a way to sign in to your account such that the bot knows that you are a member of the slack channel

Back end:
- [ ] Read through the slack channel to obtain the list of teams contained within the channel
- [ ] Create a ListOfTeams database which stores all of the teams read from the above operation onto the MongoDb database after each update occurs
- [ ] Update your ListOfTeams database before each time the program outputs the list of teams such that it makes sure the list of teams that are being output is up to date with any changes that may have occurred.
- [ ] Delete your original database prior to calling update, read, and create such that you can have a fresh database to utilize

Testing:

- [ ] Front end tests pass and there is adequate coverage
- [ ] Back end tests pass and there is adequate coverage
